import os
import shutil
import logging
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pykasso as pk
import CFPy as cfpy
import flopy
import flopy.utils.binaryfile as bf
from scipy.stats import qmc

from .recharge import FlexModelFrac

# ── Default fracture families ─────────────────────────────────────────────────

_DEFAULT_FRACTURES = {
    "family_01": {
        "density": 0.000007,
        "orientation": [135, 160],
        "dip": [90, 160],
        "length": [300, 400],
        "alpha": 1.5,
    },
    "family_02": {
        "density": 0.000007,
        "orientation": [45, 80],
        "dip": [90, 120],
        "length": [500, 700],
        "alpha": 1.5,
    },
    "family_03": {
        "density": 0.000004,
        "orientation": [0, 60],
        "dip": [90, 120],
        "length": [500, 700],
        "alpha": 1.5,
    },
}

_VLAB_DIR = Path(__file__).parent


# ── Data ──────────────────────────────────────────────────────────────────────

class Data:
    """Daily precipitation and evaporation time series."""

    def __init__(self, prec: pd.Series, evap: pd.Series):
        self.prec = prec
        self.evap = evap

    @classmethod
    def from_csv(cls, prec_path, evap_path):
        prec = pd.read_csv(
            prec_path, parse_dates=True, index_col=[0],
            sep=";", usecols=[0, 2], dayfirst=True,
        ).resample("D").sum().squeeze()
        evap = pd.read_csv(
            evap_path, parse_dates=True, index_col=[0],
            sep=";", dayfirst=True,
        ).squeeze()
        return cls(prec, evap)

    @classmethod
    def default(cls):
        return cls.from_csv(_VLAB_DIR / "prec.csv", _VLAB_DIR / "evap.csv")


# ── Epikarst ──────────────────────────────────────────────────────────────────

class Epikarst:
    """Soil/epikarst recharge model (FlexModelFrac by default)."""

    def __init__(self, n_tiles: int = 5):
        self.n_tiles = n_tiles
        self._model = FlexModelFrac()

    def simulate(self, data: Data, rch_params) -> np.ndarray:
        """
        Simulate total recharge (slow + quick) for the study period.

        Parameters
        ----------
        data : Data
        rch_params : array-like, shape (7,)
            [srmax, lp, ks, gamma, simax, kv, omega]

        Returns
        -------
        rch_ts : np.ndarray, shape (len(data.prec),), mm/d
        """
        n = len(data.prec)
        prec_ml = np.tile(data.prec.values.ravel(), self.n_tiles)
        evap_ml = np.tile(data.evap.values.ravel(), self.n_tiles)
        rch_slow, rch_quick = self._model.simulate(
            prec=prec_ml, evap=evap_ml, p=np.array(rch_params)
        )
        return (rch_slow + rch_quick)[n * (self.n_tiles - 1):]


# ── Parameter groups ──────────────────────────────────────────────────────────

class RechargeParams:
    """
    Recharge model parameter group.

    Parameters
    ----------
    stochastic : bool
        If True, parameters are sampled via LHS. If False, fixed values are used.
    values : dict, optional
        Override default fixed values. Used when stochastic=False.
    bounds : dict, optional
        Override default sampling bounds. Used when stochastic=True.
        Each entry should be a (low, high) tuple.
    """

    NAMES = ["srmax", "lp", "ks", "gamma", "simax", "kv", "omega"]
    _DEFAULTS = {
        "srmax": 250., "lp": 0.25, "ks": 1000.,
        "gamma": 2., "simax": 1., "kv": 5., "omega": 0.2,
    }
    _BOUNDS = {
        "srmax": (100., 500.), "lp": (0.1, 0.8), "ks": (100., 5000.),
        "gamma": (1., 5.), "simax": (0.5, 10.), "kv": (0.1, 10.),
        "omega": (0.1, 0.9),
    }

    def __init__(self, stochastic=True, values=None, bounds=None):
        self.stochastic = stochastic
        self.values = {**self._DEFAULTS, **(values or {})}
        self.bounds = {**self._BOUNDS, **(bounds or {})}
        self._samples = None


class NetworkStructure:
    """
    Network structure parameter group (stochastic: sks_seed only).

    The inlet/outlet counts, seeds, and fracture family definitions are
    fixed properties of the system — they can only be changed by passing
    a different NetworkStructure to a different System instance.

    Parameters
    ----------
    stochastic : bool
        If True, sks_seed is sampled via LHS over sks_range.
    values : dict, optional
        Override default fixed value for sks_seed.
    bounds : dict, optional
        Override sampling range, e.g. {"sks_seed": (0, 50000)}.
    n_inlets : int
        Number of inlets (sinkholes) generated by pyKasso.
    inlets_seed : int
        Random seed for inlet placement.
    outlets_seed : int
        Random seed for outlet placement.
    fracture_families : dict, optional
        pyKasso fracture family definitions. None uses the built-in default.
    """

    NAMES = ["sks_seed"]
    _DEFAULTS = {"sks_seed": 12345}
    _BOUNDS    = {"sks_seed": (0, 99999)}

    def __init__(self, stochastic=True, values=None, bounds=None,
                 n_inlets=5, inlets_seed=456, outlets_seed=7,
                 fracture_families=None):
        self.stochastic = stochastic
        self.values = {**self._DEFAULTS, **(values or {})}
        self.bounds = {**self._BOUNDS, **(bounds or {})}
        self._samples = None
        # fixed structural config
        self.n_inlets = n_inlets
        self.inlets_seed = inlets_seed
        self.outlets_seed = outlets_seed
        self.fracture_families = fracture_families if fracture_families is not None \
            else _DEFAULT_FRACTURES


class NetworkProperties:
    """
    Conduit network property parameter group.

    Parameters
    ----------
    stochastic : bool
    values : dict, optional
        Override fixed values for k_exchange, diameter, rheight, cad.
    bounds : dict, optional
        Override sampling bounds.
    """

    NAMES = ["k_exchange", "diameter", "rheight", "cad"]
    _DEFAULTS = {"k_exchange": 1e-4, "diameter": 0.5, "rheight": 0.02, "cad": 0.01}
    _BOUNDS = {
        "k_exchange": (1e-5, 1e-4),
        "diameter":   (0.1, 1.0),
        "rheight":    (0.001, 0.1),
        "cad":        (0.01, 0.5),
    }

    def __init__(self, stochastic=True, values=None, bounds=None):
        self.stochastic = stochastic
        self.values = {**self._DEFAULTS, **(values or {})}
        self.bounds = {**self._BOUNDS, **(bounds or {})}
        self._samples = None


class AquiferParams:
    """
    Matrix aquifer parameter group.

    Parameters
    ----------
    stochastic : bool
    values : dict, optional
        Override fixed values for hk, ss, sy.
    bounds : dict, optional
        Override sampling bounds.
    """

    NAMES = ["hk", "ss", "sy"]
    _DEFAULTS = {"hk": 1e-4, "ss": 1e-4, "sy": 0.01}
    _BOUNDS = {
        "hk": (1e-5, 1e-4),
        "ss": (1e-5, 1e-3),
        "sy": (0.01, 0.3),
    }

    def __init__(self, stochastic=True, values=None, bounds=None):
        self.stochastic = stochastic
        self.values = {**self._DEFAULTS, **(values or {})}
        self.bounds = {**self._BOUNDS, **(bounds or {})}
        self._samples = None


# ── Network ───────────────────────────────────────────────────────────────────

class Network:
    """Outputs of the pyKasso network generation phase.

    Passed to Groundwater.run_modflow / System.simulate_from_network to run
    MODFLOW + CFP without repeating the (expensive) network generation step.
    """

    def __init__(self, validator, idxs_spring, idxs_inlet):
        self.validator = validator      # GeneralValidator with valid_network inside
        self.idxs_spring = idxs_spring  # [col, row, lay] 1-based MODFLOW indices
        self.idxs_inlet = idxs_inlet    # list of [col, row, lay]


# ── Groundwater ───────────────────────────────────────────────────────────────

class Groundwater:
    """pyKasso network generation + MODFLOW + CFP simulation.

    Holds fixed structural / solver settings only. All stochastic parameters
    (hk, ss, sy, k_exchange, diameter, rheight, cad, sks_seed) are passed at
    runtime via the params dict from System._get_params().
    """

    def __init__(
        self,
        exe_name="C:/WRDAPP/CFPv2.exe",
        nz=10,
        vka_ratio=1.0,
        H_init=75.0,
        mftol=1e-4,
        mfrelax=0.98,
        mxiter=5000,
        tortuosity=1.0,
        lcritrey=500,
        hcritrey=5000,
        cfptol=1e-5,
        cfprelax=0.98,
        perlen=86400,
        time_unit=1,
    ):
        self.exe_name = exe_name
        self.nz = nz
        self.vka_ratio = vka_ratio
        self.H_init = H_init
        self.mftol = mftol
        self.mfrelax = mfrelax
        self.mxiter = mxiter
        self.tortuosity = tortuosity
        self.lcritrey = lcritrey
        self.hcritrey = hcritrey
        self.cfptol = cfptol
        self.cfprelax = cfprelax
        self.perlen = perlen
        self.time_unit = time_unit

    def plot_network(self, network, inlet_indices, spring_index, n_rows, n_cols):
        fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(10, 5))
        network_plot = network.copy()
        network_plot[network_plot == 0.] = np.nan
        im = ax.matshow(network_plot, cmap="cividis", vmin=2., vmax=11.)
        plt.colorbar(im, label="Elevation [m]", shrink=0.7)
        inlets_ = np.array(inlet_indices)
        ax.scatter(inlets_[:, 0] - 1, inlets_[:, 1] - 1, c="r", marker="v",
                   edgecolor="k", s=70)
        ax.scatter([spring_index[0]], [spring_index[1]], c="cyan", marker=">",
                   edgecolor="k", s=70, clip_on=False, zorder=1000)
        ax.set_xlabel("Col")
        ax.set_ylabel("Row")
        ax.set_xlim(-0.5, n_cols - 0.5)
        ax.set_ylim(-0.5, n_rows - 0.5)
        plt.show()

    def simulate(self, system, recharge_ts, params: dict, proj_name, working_dir,
                 n_stress_periods=None, plot_network=False):
        """Run pyKasso + MODFLOW + CFP (full pipeline)."""
        if n_stress_periods is not None:
            recharge_ts = recharge_ts[:n_stress_periods]
        network = self._generate_network(
            proj_name=proj_name,
            sks_seed=int(params["sks_seed"]),
            n_inlets=int(params["n_inlets"]),
            inlets_seed=int(params["inlets_seed"]),
            outlets_seed=int(params["outlets_seed"]),
            fracture_families=params["fracture_families"],
            n_rows=system.n_rows,
            n_cols=system.n_cols,
            delr=system.delr,
            delc=system.delc,
            lay_elevs=system.lay_elevs,
            chb_spring=system.chb_spring,
            working_dir=str(working_dir),
            plot_network=plot_network,
        )
        return self._run_modflow(
            network=network,
            proj_name=proj_name,
            recharge_ts=recharge_ts,
            hk=float(params["hk"]),
            ss=float(params["ss"]),
            sy=float(params["sy"]),
            k_exchange=float(params["k_exchange"]),
            diameter=float(params["diameter"]),
            rheight=float(params["rheight"]),
            cad=float(params["cad"]),
            n_rows=system.n_rows,
            n_cols=system.n_cols,
            n_lays=system.n_lays,
            delr=system.delr,
            delc=system.delc,
            lay_elevs=system.lay_elevs,
            chb_spring=system.chb_spring,
            working_dir=str(working_dir),
        )

    def generate_network(self, system, params: dict, proj_name, working_dir,
                         plot_network=False) -> "Network":
        """Run the pyKasso network generation phase only.

        Returns a Network object that can be passed to run_modflow later,
        allowing many networks to be generated independently of MODFLOW runs.
        """
        return self._generate_network(
            proj_name=proj_name,
            sks_seed=int(params["sks_seed"]),
            n_inlets=int(params["n_inlets"]),
            inlets_seed=int(params["inlets_seed"]),
            outlets_seed=int(params["outlets_seed"]),
            fracture_families=params["fracture_families"],
            n_rows=system.n_rows,
            n_cols=system.n_cols,
            delr=system.delr,
            delc=system.delc,
            lay_elevs=system.lay_elevs,
            chb_spring=system.chb_spring,
            working_dir=str(working_dir),
            plot_network=plot_network,
        )

    def run_modflow(self, system, network: "Network", recharge_ts, params: dict,
                    proj_name, working_dir, n_stress_periods=None):
        """Run MODFLOW + CFP given a pre-generated Network object.

        Parameters
        ----------
        network : Network
            Output of generate_network / _generate_network.
        recharge_ts : np.ndarray
            Recharge time series (mm/d).
        params : dict
            Full parameter dict from System._get_params(). Must contain:
            hk, ss, sy, k_exchange, diameter, rheight, cad.

        Returns
        -------
        success : bool
        Q_out   : pd.Series  spring discharge time series
        heads   : np.ndarray  shape (n_pers, n_lays, n_rows, n_cols)
        """
        if n_stress_periods is not None:
            recharge_ts = recharge_ts[:n_stress_periods]
        return self._run_modflow(
            network=network,
            proj_name=proj_name,
            recharge_ts=recharge_ts,
            hk=float(params["hk"]),
            ss=float(params["ss"]),
            sy=float(params["sy"]),
            k_exchange=float(params["k_exchange"]),
            diameter=float(params["diameter"]),
            rheight=float(params["rheight"]),
            cad=float(params["cad"]),
            n_rows=system.n_rows,
            n_cols=system.n_cols,
            n_lays=system.n_lays,
            delr=system.delr,
            delc=system.delc,
            lay_elevs=system.lay_elevs,
            chb_spring=system.chb_spring,
            working_dir=str(working_dir),
        )

    def _generate_network(self, proj_name, sks_seed, n_inlets, inlets_seed,
                          outlets_seed, fracture_families, n_rows, n_cols,
                          delr, delc, lay_elevs, chb_spring, working_dir,
                          plot_network=False) -> "Network":
        os.chdir(working_dir)

        dz = (lay_elevs[0] - lay_elevs[-1]) / self.nz
        grid_parameters = {
            "x0": 0, "y0": 0, "z0": 0,
            "nx": n_cols, "ny": n_rows, "nz": self.nz,
            "dx": delr, "dy": delc, "dz": dz,
        }

        app = pk.pykasso()
        app.new_project(name=proj_name + "_pyKasso", grid_parameters=grid_parameters)
        app.visualizer.notebook = True

        model_parameters = {
            "sks": {"seed": sks_seed, "algorithm": "Riemann3", "ratio": 0.1},
            "domain": {
                "bedrock": np.zeros((n_cols, n_rows)),
                "water_table": np.full((n_cols, n_rows), chb_spring),
            },
            "outlets": {
                "seed": outlets_seed, "number": 1,
                "subdomain": "domain_borders_bottom",
            },
            "inlets": {
                "number": n_inlets, "seed": inlets_seed,
                "subdomain": "domain_surface",
            },
            "fractures": {"generate": fracture_families},
        }
        np.random.seed(sks_seed)
        app.model.generate(model_parameters=model_parameters)

        network    = np.moveaxis(np.array(app.model.maps["karst"][0]), 1, 0)
        elevations = np.moveaxis(app.model.node_elev_arr, 1, 0)
        outlets    = np.moveaxis(app.model.maps["outlets"], 1, 0)

        network    = np.max(network, axis=-1)[::-1, :]
        elevations = np.max(elevations, axis=-1)[::-1, :]
        outlets    = np.nanmax(outlets, axis=-1)[::-1, :]

        validator = cfpy.preprocessing.GeneralValidator(
            network=network, elevations=elevations
        )
        validator.validate_network_elevations()

        sp = np.argwhere(~np.isnan(outlets))[0]
        idxs_spring = [int(sp[1] + 1), int(sp[0] + 1), 1]

        df = pd.DataFrame.from_dict(
            app.model.vectors["nodes"], orient="index",
            columns=["x", "y", "z", "type"],
        )
        idxs_inlet = []
        for _, row in df[df["type"] == "inlet"].iterrows():
            col, r = app.model.grid.get_indices((row["x"], row["y"]))
            idxs_inlet.append([int(col[0]) + 1, n_rows - int(r[0]), 1])

        if plot_network:
            self.plot_network(
                validator.network, idxs_inlet, idxs_spring, n_rows, n_cols
            )

        return Network(validator, idxs_spring, idxs_inlet)

    def _run_modflow(self, network: "Network", proj_name, recharge_ts, hk, ss, sy,
                     k_exchange, diameter, rheight, cad, n_rows, n_cols, n_lays,
                     delr, delc, lay_elevs, chb_spring, working_dir):
        lay_elevs_array = [
            np.ones((n_rows, n_cols)) * lay_elevs[0],
            np.ones((n_rows, n_cols)) * lay_elevs[1],
        ]

        modflow_dir = os.path.join(working_dir, proj_name + "_modflow")
        os.makedirs(modflow_dir, exist_ok=True)
        os.chdir(modflow_dir)

        modelname = "pyKasso_example"
        mf = flopy.modflow.Modflow(modelname, exe_name=self.exe_name)

        n_pers = len(recharge_ts) + 1
        flopy.modflow.ModflowDis(
            mf, n_lays, n_rows, n_cols, n_pers,
            delr, delc, top=lay_elevs[0], botm=lay_elevs[1],
            perlen=self.perlen,
            nstp=[1] * n_pers,
            steady=[1] + [0] * (n_pers - 1),
            itmuni=self.time_unit, lenuni=2,
        )

        flopy.modflow.ModflowBas(
            mf, ibound=np.ones((n_lays, n_rows, n_cols), dtype=np.int32),
            strt=self.H_init,
        )

        flopy.modflow.ModflowLpf(
            mf, laytyp=1, chani=1, layvka=0, laywet=0,
            ipakcb=50, hdry=999., hk=hk, hani=1,
            vka=hk * self.vka_ratio, wetdry=0, ss=ss, sy=sy,
        )

        flopy.modflow.ModflowOc(
            mf,
            stress_period_data={
                (i, 0): ["save head", "print budget"] for i in range(n_pers)
            },
        )

        flopy.modflow.ModflowPcg(
            mf, mxiter=self.mxiter, iter1=self.mxiter, npcond=1,
            hclose=self.mftol, rclose=self.mftol, relax=self.mfrelax,
            nbpol=2, iprpcg=5, mutpcg=0, damp=0.99, ihcofadd=9999,
        )

        rch_mean = np.mean(recharge_ts) / 86400 / 1000  # mm/d → m/s
        rech = {0: rch_mean}
        for i, r in enumerate(recharge_ts):
            rech[i + 1] = r / 86400 / 1000
        flopy.modflow.mfrch.ModflowRch(mf, nrchop=1, ipakcb=50, rech=rech)

        mf.write_input()
        network.validator.export_network()
        network.validator.generate_nbr(
            path=modflow_dir, nrows=n_rows, ncols=n_cols,
            nlays=n_lays, nplanes=1, layer_elevations=lay_elevs_array,
        )

        nbr = cfpy.nbr()
        bot_elev, cond_elev = nbr.nbr_read()
        nbr_data = nbr.nbr(bot_elev, cond_elev)

        n_nodes = len(nbr_data[0])
        n_pipes = len(nbr_data[5])

        pipe_data = [
            nbr_data[5],
            (np.ones(n_pipes) * diameter).tolist(),
            (np.ones(n_pipes) * self.tortuosity).tolist(),
            (np.ones(n_pipes) * rheight).tolist(),
            (np.ones(n_pipes) * self.lcritrey).tolist(),
            (np.ones(n_pipes) * self.hcritrey).tolist(),
        ]

        n_head = (np.ones(n_nodes) * -1).tolist()
        if network.idxs_spring not in nbr_data[2]:
            raise ValueError(f"Spring node {network.idxs_spring} not found in network.")
        n_head[nbr_data[2].index(network.idxs_spring)] = chb_spring

        kex_data  = [nbr_data[0], (np.ones(n_nodes) * k_exchange).tolist()]
        cads_data = (np.ones(n_nodes) * cad).tolist()

        cfp_str = cfpy.cfp(
            mode=1, nnodes=n_nodes, npipes=n_pipes, nlay=n_lays,
            nbr_data=nbr_data, geoheight=cond_elev, sa_exchange=0,
            epsilon=self.cfptol, niter=2000, relax=self.cfprelax,
            p_nr=0, cond_data=pipe_data,
            n_head=[nbr_data[0], n_head],
            k_exchange=kex_data, ncl=0, cl=0, ltemp=10,
            condl_data=0, cads=cads_data,
        ).cfp()

        coc_str = cfpy.coc(
            nnodes=n_nodes, node_numbers=nbr_data[0], n_nts=1,
            npipes=n_pipes, pipe_numbers=nbr_data[5], t_nts=1,
        ).coc()

        p_crch = np.zeros(n_nodes).tolist()
        for idx in network.idxs_inlet:
            if idx not in nbr_data[2]:
                raise ValueError(f"Inlet node {idx} not found in network.")
            p_crch[nbr_data[2].index(idx)] = 1.0

        crch_str = cfpy.crch(
            iflag_crch=1, nper=n_pers,
            node_numbers=nbr_data[0], p_crch=p_crch,
        ).crch()

        cfpy.write_input(
            modelname=modelname,
            data_strings=[coc_str, crch_str, cfp_str],
            file_extensions=["coc", "crch", "cfp"],
        ).write_input()

        cfpy.update_nam(
            modelname=modelname, mode=1,
            cfp_unit_num=52, crch_unit_num=53, coc_unit_num=54,
        ).update_nam()

        success, _ = mf.run_model(silent=True)

        hds = bf.HeadFile(os.path.join(modflow_dir, f"{modelname}.hds"))
        heads = hds.get_alldata()

        node_arr = np.array(nbr_data[2])
        idx = np.where((node_arr == network.idxs_spring).all(axis=1))[0] + 1
        flows = pd.read_fwf(
            os.path.join(modflow_dir, f"NODE{str(idx[0]).zfill(8)}.OUT")
        )
        Q_out = (
            flows["QMAT"] + flows["QCADS"]
            + flows["QTUB1"] + flows["QTUB2"] + flows["QTUB3"]
            + flows["QTUB4"] + flows["QTUB5"] + flows["QTUB6"]
        )

        return success, Q_out, heads


# ── System ────────────────────────────────────────────────────────────────────

class System:
    """
    Central object for a virtual karst laboratory.

    Stochastic parameter groups can be independently toggled:

        s = vlab.System(
            recharge_params=vlab.RechargeParams(stochastic=True),
            network_structure=vlab.NetworkStructure(stochastic=True),
            network_properties=vlab.NetworkProperties(stochastic=False),
            aquifer_params=vlab.AquiferParams(stochastic=False),
        )

    Each integer random_state maps to one row of the jointly generated
    LHS parameter table (param_samples). random_state=None uses defaults.

    Parameters
    ----------
    name : str
    n_rows, n_cols, n_lays : int
    delr, delc : float  cell size (m)
    lay_elevs : list[float]  [top, bottom] elevation (m)
    chb_spring : float  fixed head at spring (m)
    data : Data or None
    epikarst : Epikarst or None
    groundwater : Groundwater or None
    n_stress_periods : int or None
        Transient stress periods for MODFLOW. None uses full recharge length.
    recharge_params : RechargeParams or None
    network_structure : NetworkStructure or None
    network_properties : NetworkProperties or None
    aquifer_params : AquiferParams or None
    """

    def __init__(
        self,
        name="vlab",
        n_rows=50,
        n_cols=100,
        n_lays=1,
        delr=25.0,
        delc=25.0,
        lay_elevs=None,
        chb_spring=10.0,
        data=None,
        epikarst=None,
        groundwater=None,
        n_stress_periods=None,
        recharge_params=None,
        network_structure=None,
        network_properties=None,
        aquifer_params=None,
    ):
        self.name = name
        self.n_rows = n_rows
        self.n_cols = n_cols
        self.n_lays = n_lays
        self.delr = delr
        self.delc = delc
        self.lay_elevs = lay_elevs if lay_elevs is not None else [50.0, 0.0]
        self.chb_spring = chb_spring
        self.n_stress_periods = n_stress_periods

        self.data        = data        if data        is not None else Data.default()
        self.epikarst    = epikarst    if epikarst    is not None else Epikarst()
        self.groundwater = groundwater if groundwater is not None else Groundwater()

        self.recharge_params    = recharge_params    if recharge_params    is not None else RechargeParams()
        self.network_structure  = network_structure  if network_structure  is not None else NetworkStructure()
        self.network_properties = network_properties if network_properties is not None else NetworkProperties()
        self.aquifer_params     = aquifer_params     if aquifer_params     is not None else AquiferParams()

        self._param_samples: pd.DataFrame | None = None

    def _groups(self):
        return [
            self.recharge_params,
            self.network_structure,
            self.network_properties,
            self.aquifer_params,
        ]

    # ── Parameter sampling ────────────────────────────────────────────────────

    def generate_samples(self, n_samples=500, seed=1) -> pd.DataFrame:
        """
        Generate a joint LHS table over all active stochastic dimensions.

        Each stochastic group contributes its parameters as columns; fixed
        groups contribute nothing. The sks_seed column is rounded to int.

        Returns
        -------
        param_samples : pd.DataFrame, shape (n_samples, n_stochastic_dims)
        """
        stochastic_groups = [g for g in self._groups() if g.stochastic]

        all_names = []
        all_lows  = []
        all_highs = []
        for g in stochastic_groups:
            for name in g.NAMES:
                all_names.append(name)
                lo, hi = g.bounds[name]
                all_lows.append(lo)
                all_highs.append(hi)

        D = len(all_names)
        if D == 0:
            self._param_samples = pd.DataFrame(index=range(n_samples))
            for g in self._groups():
                g._samples = np.empty((n_samples, 0))
            return self._param_samples

        raw    = qmc.LatinHypercube(d=D, rng=seed).random(n=n_samples)
        scaled = qmc.scale(raw, all_lows, all_highs)

        # split back into per-group sample arrays
        col = 0
        for g in stochastic_groups:
            n = len(g.NAMES)
            g._samples = scaled[:, col:col + n].copy()
            col += n

        # sks_seed must be integer
        if self.network_structure.stochastic:
            i = self.network_structure.NAMES.index("sks_seed")
            self.network_structure._samples[:, i] = np.round(
                self.network_structure._samples[:, i]
            ).astype(int)

        self._param_samples = pd.DataFrame(scaled, columns=all_names)
        if "sks_seed" in self._param_samples.columns:
            self._param_samples["sks_seed"] = (
                self._param_samples["sks_seed"].round().astype(int)
            )

        return self._param_samples

    @property
    def param_samples(self) -> pd.DataFrame:
        if self._param_samples is None:
            self.generate_samples()
        return self._param_samples

    def _get_params(self, random_state) -> dict:
        """
        Assemble a full parameter dict for the given realization.

        For stochastic groups: uses LHS sample row if random_state is an int,
        or group defaults if random_state is None.
        For fixed groups: always uses group defaults.
        """
        if random_state is not None:
            _ = self.param_samples  # trigger sample generation if needed

        d = {}
        for g in self._groups():
            if g.stochastic and random_state is not None:
                for i, name in enumerate(g.NAMES):
                    val = g._samples[random_state, i]
                    d[name] = int(round(val)) if name == "sks_seed" else float(val)
            else:
                for name in g.NAMES:
                    d[name] = g.values[name]

        # fixed structural params from NetworkStructure (never stochastic)
        d["n_inlets"]          = self.network_structure.n_inlets
        d["inlets_seed"]       = self.network_structure.inlets_seed
        d["outlets_seed"]      = self.network_structure.outlets_seed
        d["fracture_families"] = self.network_structure.fracture_families

        return d

    # ── Simulate recharge ─────────────────────────────────────────────────────

    def simulate_recharge(self, random_state=None) -> np.ndarray:
        """
        Simulate total recharge for one parameter realization.

        Parameters
        ----------
        random_state : int or None
            Row index into param_samples. None uses default parameters.

        Returns
        -------
        rch_ts : np.ndarray, shape (len(data.prec),), mm/d
        """
        params = self._get_params(random_state)
        rch_params = [params[n] for n in RechargeParams.NAMES]
        return self.epikarst.simulate(self.data, rch_params)

    # ── Simulate network only ─────────────────────────────────────────────────

    def generate_network(self, random_state=None, working_dir=None, cleanup=True,
                         plot_network=False) -> "Network":
        """
        Run the pyKasso network generation phase only.

        Parameters
        ----------
        random_state : int or None
            Row index into param_samples. None uses default parameters.
        working_dir : str, Path, or None
            Base directory for model files. Defaults to the vlab/ directory.
        cleanup : bool
            Remove the pyKasso run directory after generation.
        plot_network : bool
            Show a network plot after generation.

        Returns
        -------
        network : Network
            Validated network object; pass to simulate_from_network later.
        """
        params = self._get_params(random_state)

        tag       = str(random_state) if random_state is not None else "default"
        proj_name = f"{self.name}_{tag}"
        base_dir  = str(working_dir) if working_dir is not None else str(Path.cwd())
        orig_dir  = os.getcwd()

        try:
            os.chdir(base_dir)
            _flush_pykasso_loggers()
            network = self.groundwater.generate_network(
                system=self,
                params=params,
                proj_name=proj_name,
                working_dir=base_dir,
                plot_network=plot_network,
            )
        finally:
            _flush_pykasso_loggers()
            os.chdir(orig_dir)
            if cleanup:
                d = os.path.join(base_dir, proj_name + "_pyKasso")
                if os.path.exists(d):
                    shutil.rmtree(d)

        return network

    # ── Simulate from pre-generated network ───────────────────────────────────

    def simulate_from_network(self, network: "Network", random_state=None,
                              working_dir=None, cleanup=True):
        """
        Run MODFLOW + CFP given a pre-generated Network object.

        Recharge is simulated internally using random_state, consistent with
        how simulate_full works.

        Parameters
        ----------
        network : Network
            Output of generate_network.
        random_state : int or None
            Row index into param_samples (controls recharge + MODFLOW params).
            None uses default parameters.
        working_dir : str, Path, or None
        cleanup : bool
            Remove the MODFLOW run directory after the run.

        Returns
        -------
        success : bool
        Q_out   : pd.Series  spring discharge time series
        heads   : np.ndarray  shape (n_pers, n_lays, n_rows, n_cols)
        """
        params = self._get_params(random_state)

        rch_params = [params[n] for n in RechargeParams.NAMES]
        rch_ts = self.epikarst.simulate(self.data, rch_params)

        tag       = str(random_state) if random_state is not None else "default"
        proj_name = f"{self.name}_{tag}"
        base_dir  = str(working_dir) if working_dir is not None else str(Path.cwd())
        orig_dir  = os.getcwd()

        try:
            os.chdir(base_dir)
            _flush_pykasso_loggers()
            success, Q_out, heads = self.groundwater.run_modflow(
                system=self,
                network=network,
                recharge_ts=rch_ts,
                params=params,
                proj_name=proj_name,
                working_dir=base_dir,
                n_stress_periods=self.n_stress_periods,
            )
        finally:
            _flush_pykasso_loggers()
            os.chdir(orig_dir)
            if cleanup:
                d = os.path.join(base_dir, proj_name + "_modflow")
                if os.path.exists(d):
                    shutil.rmtree(d)

        return success, Q_out, heads

    # ── Simulate full ─────────────────────────────────────────────────────────

    def simulate_full(self, random_state=None, working_dir=None, cleanup=True,
                      plot_network=False):
        """
        Run the complete pipeline: recharge → karst network → MODFLOW + CFP.

        Parameters
        ----------
        random_state : int or None
            Row index into param_samples. None uses default parameters.
        working_dir : str, Path, or None
            Base directory for model files. Defaults to the vlab/ directory.
        cleanup : bool
            Remove pyKasso and modflow run directories after the run.
        plot_network : bool
            Show a network plot after pyKasso generation.

        Returns
        -------
        success : bool
        Q_out   : pd.Series  spring discharge time series
        heads   : np.ndarray shape (n_pers, n_lays, n_rows, n_cols)
        """
        network = self.generate_network(
            random_state=random_state,
            working_dir=working_dir,
            cleanup=cleanup,
            plot_network=plot_network,
        )
        return self.simulate_from_network(
            network=network,
            random_state=random_state,
            working_dir=working_dir,
            cleanup=cleanup,
        )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _flush_pykasso_loggers():
    """Close and remove all root logger handlers (Windows file-lock workaround)."""
    root = logging.getLogger()
    for h in root.handlers[:]:
        h.close()
        root.removeHandler(h)
