 ##################
### SKS SETTINGS ###
 ##################

---
############
### Grid ###
############

x0   : 0
y0   : 0
xnum : 50
ynum : 100
dx   : 10
dy   : 10

###############
### Polygon ###
###############

data_has_polygon : False
polygon_data     : ''

####################
### PointManager ###
####################

###Inlets
# 'random'    - full random points 
# 'import'    - import points
# 'composite' - add n random points to imported points
inlets_mode   : 'import'
inlets_data   : [[155, 855], [485, 455], [275, 355]]
inlets_number : 3
inlets_shuffle : False
inlets_per_outlet : [3]
inlets_importance : [3]

###Outlets
# 'random'    - full random points 
# 'import'    - import points
# 'composite' - add n random points to imported points
outlets_mode   : 'import'
outlets_data   : [[255, 0]]
outlets_number : 1
outlets_shuffle : False
outlets_importance : [1]

######################
### GeologyManager ###
######################

#Topography
topography_mode      : 'null'          #null, gslib, csv, or image
topography_datafile  : ''

#Geology
geological_mode      : 'null'        #null, import, gslib, csv, or image
geological_datafile  : ''

#Orientation (not needed for isotropic)
orientation_mode     : 'null'       
orientation_datafile : ''

#Faults
faults_mode          : 'null'       #null, import, gslib, csv, image
faults_datafile      : ''

#Fractures
fractures_mode       : 'random'        #null, import, gslib, csv, image, or random
fractures_datafile   : ''

# If fractures mode is 'generate'
fractures_densities       : [0.00005,0.0005]
fractures_min_orientation : [    340,   10]
fractures_max_orientation : [     20,  350]

# For fracture size
fractures_alpha : 2
fractures_min_length : 20
fractures_max_length : 500

###############################
### Fast-Marching Algorithm ###
###############################
algorithm : "Isotropic2"

cost_out       : 0.999
cost_aquifer   : 0.4
cost_aquiclude : 0.8
cost_faults    : 0.2
cost_fractures : 0.01
cost_conduits  : 0.3
cost_ratio     : 0.5

### Formation to consider and FMM code associated
geology_id       : [1,2] # Only for 'import' geological mode
geology_cost : [cost_aquifer,cost_aquiclude]

#############
### Other ###
#############

rand_seed : 12
verbosity : 0
...
