 ##################
### SKS SETTINGS ###
 ##################

---
############
### Grid ###
############

x0   : 0
y0   : 0
xnum : 100
ynum : 100
dx   : 10
dy   : 10

###############
### Polygon ###
###############

data_has_polygon : False
polygon_data     : ''

####################
### PointManager ###
####################

###Inlets
# 'random'    - full random points 
# 'import'    - import points
# 'composite' - add n random points to imported points
inlets_mode   : 'random'
inlets_data   : ''
inlets_number : 10
inlets_shuffle : False
inlets_per_outlet : [10]
inlets_importance : [1]

###Outlets
# 'random'    - full random points 
# 'import'    - import points
# 'composite' - add n random points to imported points
outlets_mode   : 'import'
outlets_data   : [[505, 0]]
outlets_number : 1
outlets_shuffle : False
outlets_importance : [1]

######################
### GeologyManager ###
######################

#Topography
topography_mode      : 'null'          #null, gslib, csv, or image
topography_datafile  : ''

#Geology
geological_mode      : 'null'        #null, import, gslib, csv, or image
geological_datafile  : ''

#Orientation (not needed for isotropic)
orientation_mode     : 'null'       
orientation_datafile : ''

#Faults
faults_mode          : 'null'       #null, import, gslib, csv, image
faults_datafile      : ''

#Fractures
fractures_mode       : 'random'        #null, import, gslib, csv, image, or random
fractures_datafile   : ''

# If fractures mode is 'generate'
fractures_densities       : [0.00005,0.0001]
fractures_min_orientation : [    340,    70]
fractures_max_orientation : [     20,   110]

# For fracture size
alpha : 2
fractures_min_length : 20
fractures_max_length : 500

###############################
### Fast-Marching Algorithm ###
###############################
algorithm : "Isotropic2" #'Isotropic2', 'Riemann2', which algo to use, see agd-hfm library doc for all options

code_out       : 0.999
code_aquifere   : 0.4
code_aquiclude : 0.8
code_faults    : 0.2
code_fractures : 0.2
code_conduits  : 0.1
code_ratio     : 0.5

### Formation to consider and FMM code associated
geology_id       : [1,2] # Only for 'import' geological mode
geology_velocity : [code_aquifere,code_aquiclude]
importance_factor : [1,2,3]

#############
### Other ###
#############

rand_seed : 0
verbosity : 0
...